#!/usr/local/cpanel/3rdparty/bin/perl
# cpanel - find-latest-version                  Copyright(c) 2020 cPanel, L.L.C.
#                                                           All rights Reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited
#
# This provides incremental updates to existing packages in EasyApache4.
package apr::find_latest_version;

use strict;
use warnings;

use lib "../ea-tools/lib/ea4_tool";    # assumes ea-tools is checked out next to this repo
use ea4_tool::util ();

unless ( caller() ) {
    ea4_tool::util::find_latest_version( \&_get_required, \&_add_sum );
}

###############
#### helpers ##
###############

sub _sort_version
{
    my ($a_major, $a_minor, $a_nano) = split (/\./, $a);
    my ($b_major, $b_minor, $b_nano) = split (/\./, $b);

    return 1 if ($a_major > $b_major);
    return -1 if ($a_major < $b_major);
    return 1 if ($a_minor > $b_minor);
    return -1 if ($a_minor < $b_minor);
    return 1 if ($a_nano > $b_nano);
    return -1 if ($a_nano < $b_nano);
    return 0;
}

sub _get_required {
    my ($http) = @_;

    my $res = $http->get("https://dist.libuv.org/dist/");
    if ( !$res->{success} ) {
        die "Could not GET apr dist page ($res->{status} $res->{reason})\n";
    }

    my @libuv = sort _sort_version ( $res->{content} =~ m{href="v([0-9]+\.[0-9]+\.[0-9]+)/"}g );
    if ( !@libuv ) {
        die "Could not find libuv versions\n";
    }

    my $version = $libuv[-1];
    my $name    = "libuv-v$version.tar.gz";
    my $url     = "https://dist.libuv.org/dist/v1.39.0/libuv-v$version.tar.gz";

    return ( $version, $url, $name );
}

sub _add_sum {
    my ( $http, $hr ) = @_;

    # TODO: checksum
    #
    return;
}

